language: php
php:
  - '7.4'
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
script:
  - ./vendor/bin/phpcs
  - composer test -- --coverage-clover=./tests/coverage/clover.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
